spring.application.name=smart-hospital-management-system

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/hospital_db
spring.datasource.username=postgres
spring.datasource.password=Sumit@4321

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# PostgreSQL Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server Port
server.port=8080
jwt.secret=ThisIsMySuperSecretKeyForSmartHospitalManagementSystemProject2026ThisKeyMustBeLongEnough
jwt.expiration=86400000